alert tcp any any -> any any (msg:"Matched content tcp"; content:"get")
alert http any any -> any any (msg:"Rule matched http"; content:"example.com")
alert http any any -> any any (msg:"Threshold Test Rule"; sid:1000001; content: "get"; threshold:type limit, track by_src, count 3, seconds 30;)
